introduce mvn wrapper / mvnw
carbynestack/castor pull request #23
Opened 2022-03-14 15:38 UTC by grafjo

2022-03-15 15:14 UTC, strieflin requested changes
See https://github.com/carbynestack/amphora/pull/22#discussion_r827087715.

2022-03-17 09:19 UTC, grafjo commented
> See [carbynestack/amphora#22 (comment)](https://github.com/carbynestack/amphora/pull/22#discussion_r827087715).

requested changes are done

2022-03-18 08:58 UTC, strieflin requested changes

2022-03-18 08:58 UTC, strieflin commented on 3RD-PARTY-LICENSES/sbom.xml
> +<attributionReport>
Discussed this with @sbckr. The `sbom.xml` should contain only things that are shipped in binary form (e.g. jar or docker image). The `maven-license-plugin` is not executed for the top-level `castor` module as it is `pom`-packaged. @grafjo: Please remove the `sbom.xml` file completely. The other files in the `3RD-PARTY-LICENSES` folder should be kept as we have to still fulfill the license obligations for the maven wrapper scripts.

2022-03-21 10:23 UTC, Lila84 commented on 3RD-PARTY-LICENSES/sbom.xml
> +<attributionReport>
sbom.xml is removed

2022-03-21 10:28 UTC, strieflin approved these changes
LGTM

2022-03-21 10:29 UTC, merged